[project]
name = "eco-sense"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "attrs>=25.4.0",
    "bluepy>=1.3.0",
    "construct>=2.10.70",
    "typer>=0.21.1",
]
